In [1]:
import numpy as np

In [2]:
np.__version__

'1.19.2'

In [3]:
a = np.array([1,2,3,4,5]) # 使用 list

In [4]:
a

array([1, 2, 3, 4, 5])

In [5]:
b= np.array((6,7,8)) # 使用 元組

In [6]:
b

array([6, 7, 8])

In [7]:
type(a),type(b)

(numpy.ndarray, numpy.ndarray)

In [8]:
np.array(1, 2, 3)

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [9]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(2,10,2)

array([2, 4, 6, 8])

In [11]:
np.arange(2,8,2)

array([2, 4, 6])

In [12]:
np.arange(1.0, 3.0, 0.5, dtype='float64')

array([1. , 1.5, 2. , 2.5])

In [13]:
a = np.arange(0.13, 0.16, step=0.01)
print("沒有包含結束值：", a)
b = np.arange(0.12, 0.16, step=0.01)
print("包含結束值：", b)

沒有包含結束值： [0.13 0.14 0.15]
包含結束值： [0.12 0.13 0.14 0.15 0.16]


In [14]:
#有時會包含結束值但有時候不會

In [15]:
np.linspace(2, 10, num=4, endpoint=False)

array([2., 4., 6., 8.])

In [16]:
# 顯示間值值
np.linspace(2.0, 3.0, num=5, retstep=True)

(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)

In [17]:
a = np.array([[1, 2, 3], [4, 5, 6]])

In [18]:
print(a)

[[1 2 3]
 [4 5 6]]


In [19]:
a.shape

(2, 3)

In [20]:
b = np.array([
            [
                [1, 2, 3], [4, 5, 6],
                [7, 8, 9], [10, 11, 12]
            ],
          [
              [1, 2, 3], [4, 5, 6],
              [7, 8, 9], [10, 11, 12]
          ]
    ])

In [21]:
b.shape

(2, 4, 3)

In [22]:
b.ndim

3

In [23]:
np.array([[[1, 2, 3], [4, 5, 6],
              [7, 8, 9], [10, 11, 12]],
              [[1, 2, 3], [4, 5, 6]]])

<ipython-input-23-f231fa882b32>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  np.array([[[1, 2, 3], [4, 5, 6],


array([list([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]),
       list([[1, 2, 3], [4, 5, 6]])], dtype=object)

In [24]:
np.zeros((5, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [25]:
np.ones([2, 3])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [26]:
np.empty((2, 2, 2))

array([[[-1.28822975e-231, -3.11108620e+231],
        [ 1.97626258e-323,  0.00000000e+000]],

       [[ 0.00000000e+000,  0.00000000e+000],
        [-1.28822975e-231,  5.60603917e-309]]])

In [27]:
np.random.rand(2, 3)

array([[0.21021817, 0.87118313, 0.68898102],
       [0.03177536, 0.41008035, 0.89939527]])

In [28]:
np.random.randn(2, 3)

array([[-0.05008926, -0.0158964 ,  0.15706739],
       [ 0.05195682, -1.12166331,  1.21673532]])

In [29]:
np.random.random(10)

array([0.52023781, 0.62215108, 0.49238757, 0.50001649, 0.72644987,
       0.21653113, 0.36801329, 0.85162422, 0.63268524, 0.30281111])